### ISSUE TITLE
Action building Readme on GH-pages, not the doks demo site. 

### ISSUE THREAD

**Issue by musabukhari** [h-enk/doks-gh-pages#1]
Hi, I cloned your repo and tried running it in my org. I changed the branch in the action workflow as well as the baseURL in config/production/config.toml. I changed nothing else.

However, once the workflow deployed on my pages, it simply renders the readme there (not the doks demo site, as it does in your pages).

Please let me know if I'm overlooking something trivial or made some rookie mistake. Still very new to working with Github actions.

Thanks in advance for your help and this repo!

**Comment by h-enk** [comment]
Hi @musabukhari, did you follow [all 6 steps](https://getdoks.org/docs/recipes/deployment/#deploy-to-github-pages)?

If that did not do the trick, could you please share your repo, so I can help you out better?

**Comment by musabukhari** [comment]
Hi, I had a mistake in my gh-pages branch. Works well now. Thank you for helping!
